# Generated by Django 2.2.19 on 2022-04-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbolinfo',
            name='lot_size',
            field=models.IntegerField(default=1),
        ),
    ]
